# Generated by Django 5.0 on 2026-02-23 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('organe', models.CharField(max_length=100)),
                ('stade', models.CharField(choices=[('I', 'Stade I'), ('II', 'Stade II'), ('III', 'Stade III'), ('IV', 'Stade IV')], max_length=5)),
                ('date_diagnostic', models.DateField()),
                ('histologie', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suivi', 'Suivi'), ('critique', 'Critique'), ('decede', 'Décédé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('medecin_referent', models.ForeignKey(blank=True, limit_choices_to={'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
