# Generated by Django 6.0.2 on 2026-02-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cim10_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('chu', 'CHU'), ('ehu', 'EHU'), ('epsp', 'EPSP'), ('clinic', 'Clinique privée'), ('other', 'Autre')], default='chu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Wilayas',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='organe',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_diagnostic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='histologie',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medecin_referent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stade',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wilaya',
        ),
        migrations.AddField(
            model_name='patient',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Saisie manuelle'), ('import', 'Import CSV/Excel'), ('oedi', 'OEDI')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='merged_into_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_patients', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stade_clinique', models.CharField(blank=True, max_length=10)),
                ('stade_pathologique', models.CharField(blank=True, max_length=10)),
                ('tnm', models.CharField(blank=True, max_length=30)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('date_diagnostic', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manuel'), ('import', 'Import'), ('oedi', 'OEDI')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancers', to='patients.patient')),
                ('cancer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.cancertype')),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(max_length=100)),
                ('resultat', models.TextField(blank=True)),
                ('date_analyse', models.DateField(blank=True, null=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biological_exams', to='patients.cancer')),
            ],
        ),
        migrations.CreateModel(
            name='CancerStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('status_date', models.DateField()),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='patients.cancer')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.commune'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('compte_rendu', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_death', models.DateField()),
                ('cause_principale', models.CharField(blank=True, max_length=200)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('merged', 'Fusionné'), ('ignored', 'Ignoré')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_1', to='patients.patient')),
                ('patient_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates_as_2', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('statut_clinique', models.CharField(blank=True, max_length=100)),
                ('observation', models.TextField(blank=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='patients.cancer')),
            ],
        ),
        migrations.CreateModel(
            name='Histology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_histologique', models.CharField(blank=True, max_length=100)),
                ('grade_histologique', models.CharField(blank=True, max_length=20)),
                ('marge_chirurgicale', models.CharField(blank=True, max_length=50)),
                ('envahissement_vasculaire', models.BooleanField(blank=True, null=True)),
                ('envahissement_lymphatique', models.BooleanField(blank=True, null=True)),
                ('date_resultat', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(default='manual', max_length=20)),
                ('cancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='histology', to='patients.cancer')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.hospital'),
        ),
        migrations.CreateModel(
            name='ImagingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=100)),
                ('conclusion', models.TextField(blank=True)),
                ('date_examen', models.DateField(blank=True, null=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_exams', to='patients.cancer')),
            ],
        ),
        migrations.CreateModel(
            name='Metastasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organe', models.CharField(max_length=100)),
                ('date_detection', models.DateField(blank=True, null=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metastases', to='patients.cancer')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_traitement', models.CharField(max_length=100)),
                ('protocole', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.cancer')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='patients.wilaya'),
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='patients.wilaya'),
        ),
        migrations.CreateModel(
            name='PatientHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.habit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'habit')},
            },
        ),
        migrations.CreateModel(
            name='PatientRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='patients.patient')),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.riskfactor')),
            ],
            options={
                'unique_together': {('patient', 'risk_factor')},
            },
        ),
    ]
