# Generated by Django 6.0.2 on 2026-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_customfield_cancercustomvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CancerCustomValue',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
