# Generated by Django 6.0.2 on 2026-03-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_cancer_clinical_fields'),
        ('patients', '0004_remove_customfield_created_by_and_more'),
    ]

    operations = [
    ]
