# Generated by Django 6.0.2 on 2026-04-03 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_merge_20260330_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['date_debut']},
        ),
        migrations.AddField(
            model_name='biologicalexam',
            name='unite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='biologicalexam',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cancer',
            name='lateralite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cancer',
            name='type_histologique',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_fam_yn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_familiaux',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='autres_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='couverture_sociale',
            field=models.CharField(blank=True, choices=[('cnas', 'CNAS'), ('casnos', 'CASNOS'), ('pmsr', 'PMSR'), ('aucune', 'Aucune'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf / Veuve')], max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='base_diagnostic',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='bloc_anapath',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='cim10_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='date_symptomes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='etablissement_diag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='ganglions_envahis',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='grade_histologique',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='her2',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('equivoque', 'Équivoque'), ('negatif', 'Négatif'), ('inconnu', 'Inconnu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='localise',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='medecin_diag',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='metastatique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='recepteur_er',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Négatif'), ('inconnu', 'Inconnu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='recepteur_pr',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Négatif'), ('inconnu', 'Inconnu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='recidive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='service_diag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='sites_metastatiques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='sous_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='taille_tumorale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='type_tumeur',
            field=models.CharField(blank=True, choices=[('solide', 'Solide'), ('liquide', 'Liquide'), ('hematologique', 'Hématologique')], max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cycles_prevus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cycles_realises',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date_evaluation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description_toxicite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='grade_toxicite',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='intention',
            field=models.CharField(blank=True, choices=[('curatif', 'Curatif'), ('adjuvant', 'Adjuvant'), ('neo_adjuvant', 'Néo-adjuvant'), ('palliatif', 'Palliatif'), ('prophylactique', 'Prophylactique')], max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='jours_administration',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='ligne',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='medicaments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='protocole',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='reponse_tumorale',
            field=models.CharField(blank=True, choices=[('RC', 'Rémission complète'), ('RP', 'Rémission partielle'), ('SD', 'Stabilisation'), ('PD', 'Progression'), ('NE', 'Non évaluable')], max_length=10),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('pause', 'Pause'), ('suspendu', 'Suspendu'), ('abandonne', 'Abandonné')], default='planifie', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='type_traitement',
            field=models.CharField(choices=[('chimio', 'Chimiothérapie'), ('radio', 'Radiothérapie'), ('chirurgie', 'Chirurgie'), ('hormono', 'Hormonothérapie'), ('immuno', 'Immunothérapie'), ('targeted', 'Thérapie ciblée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='voie_administration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PathoChronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_debut', models.CharField(blank=True, max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathos_chroniques', to='patients.patient')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
