# Generated by Django 6.0.2 on 2026-04-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_demandeexamen'),
        ('patients', '0006_alter_treatment_options_biologicalexam_unite_and_more'),
    ]

    operations = [
    ]
