# Generated by Django 6.0.2 on 2026-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_merge_20260404_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeexamen',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resultat_disponible', 'Résultat disponible'), ('annule', 'Annulé')], default='en_attente', max_length=25),
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='urgence',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=15),
        ),
    ]
