# Generated by Django 6.0.4 on 2026-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_cancertype_commune_habit_hospital_riskfactor_wilaya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='wilaya_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
