# Generated by Django 6.0.5 on 2026-05-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_demandeexamen_statut_and_more'),
        ('patients', '0010_add_qr_form_notification'),
    ]

    operations = [
    ]
