# Generated by Django 6.0.5 on 2026-05-19 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_merge_20260519_0219'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-date_visite']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antecedents_fam_yn',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='antecedents_familiaux',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='autres_allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='couverture_sociale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='situation_familiale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wilaya_text',
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('resultat_disponible', 'Résultat disponible'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='urgence',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=11),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PathoChronique',
        ),
    ]
