# Generated by Django 6.0.5 on 2026-05-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_followup_options_remove_patient_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom technique')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte libre'), ('number', 'Nombre'), ('date', 'Date'), ('select', 'Liste déroulante'), ('boolean', 'Oui / Non'), ('textarea', 'Texte long')], default='text', max_length=20, verbose_name='Type de champ')),
                ('options', models.JSONField(blank=True, default=list, help_text='Pour les listes déroulantes: ["option1", "option2"]')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('section', models.CharField(choices=[('diagnostic', 'Diagnostic & Cancer'), ('biologie', 'Données biologiques'), ('traitement', 'Traitement'), ('autres', 'Autres')], default='diagnostic', max_length=50, verbose_name='Section')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'verbose_name_plural': 'Champs personnalisés',
                'ordering': ['section', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CancerCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='patients.cancer')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='patients.customfield')),
            ],
            options={
                'verbose_name': 'Valeur de champ personnalisé',
                'verbose_name_plural': 'Valeurs de champs personnalisés',
                'unique_together': {('cancer', 'field')},
            },
        ),
    ]
