# Generated by Django 5.2.11 on 2026-02-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_cancertype_commune_habit_hospital_riskfactor_wilaya_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RcpMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('presentation_reason', models.TextField(blank=True, null=True)),
                ('clinical_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcp_meetings', to='patients.cancer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rcps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RcpDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rcp_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rcp.rcpmeeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RcpDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_text', models.TextField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rcp_meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='rcp.rcpmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('rcp_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcp.rcpmeeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RcpRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rapports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('rcp_meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='rcp.rcpmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='RcpParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_rcp', models.CharField(max_length=100)),
                ('rcp_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rcp.rcpmeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rcp_meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RcpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=20)),
                ('rcp_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rcp.rcpmeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rcp_meeting', 'user')},
            },
        ),
    ]
