# Generated by Django 5.2.11 on 2026-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpdecision',
            name='signature_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rcpdecision',
            name='treatment_protocol',
            field=models.TextField(blank=True, default=''),
        ),
    ]
