# Generated by Django 5.2.11 on 2026-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0002_rcpdecision_signature_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpmeeting',
            name='vote_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rcpmeeting',
            name='vote_proposal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
