# Generated by Django 5.2.11 on 2026-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0003_rcpmeeting_vote_open_rcpmeeting_vote_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpdiscussion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='rcpdiscussion',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcpdiscussion',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Texte'), ('voice', 'Vocal')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='rcpdiscussion',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
