# Generated by Django 5.2.11 on 2026-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0004_rcpdiscussion_audio_file_rcpdiscussion_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpmeeting',
            name='video_call_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rcpmeeting',
            name='video_call_room',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
