# Generated by Django 6.0.2 on 2026-03-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0004_rcpdiscussion_audio_file_rcpdiscussion_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcpdiscussion',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='rcpdiscussion',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='rcpdiscussion',
            name='msg_type',
        ),
        migrations.AlterField(
            model_name='rcpdiscussion',
            name='message',
            field=models.TextField(),
        ),
    ]
