# Generated by Django 5.2.11 on 2026-03-06 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0005_rcpmeeting_video_call_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rcpvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rcpvote',
            name='proposal_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rcpvote',
            unique_together={('rcp_meeting', 'user', 'proposal_index')},
        ),
    ]
