# Generated by Django 6.0.5 on 2026-05-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0005_remove_rcpdiscussion_audio_file_and_more'),
        ('rcp', '0006_alter_rcpvote_unique_together_rcpvote_proposal_index_and_more'),
    ]

    operations = [
    ]
