# Generated by Django 6.0.5 on 2026-05-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcp', '0007_merge_20260517_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcpdiscussion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='rcpdiscussion',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcpdiscussion',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Texte'), ('voice', 'Vocal')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='rcpdiscussion',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
